{
    "Message": "Download in progress...",
    "CompletionMessage": "Download Successful",
    "CompletionTimeout": 7,
    "OnSuccess": "/mdkextension/Actions/capproject1/Service/DownloadOffline.action",
    "_Type": "Action.Type.ProgressBanner"
}